### ISSUE TITLE
temperature in "Temp" column isn't sufficient

### ISSUE THREAD

**Issue by bernstei** [lorisercole/thermocepstrum#65]
I'm trying to run `sportran-analysis` with a table that has a column for temperature, one for volume, and 48 for flux components (xyz x 16 independent runs).  I get the following error
```
> sportran-analysis --VOLUME 392737.783943168 -k flux -t 5 --input-format table -u metal -r --FSTAR 1 -c 2 --output TCEPS.out -- tmp2.txt
.
.
Traceback (most recent call last):
  File "/home/cluster2/bernstei/.local/bin/sportran-analysis", line 8, in <module>
    sys.exit(main())
  File "/home/cluster2/bernstei/.local/lib/python3.9/site-packages/sportran/analysis.py", line 210, in main
    run_analysis(args)
  File "/home/cluster2/bernstei/.local/lib/python3.9/site-packages/sportran/analysis.py", line 393, in run_analysis
    j = st.current.all_currents[current_type][0](currents, DT_FS=DT_FS, UNITS=units, **parameters,
  File "/home/cluster2/bernstei/.local/lib/python3.9/site-packages/sportran/current/current.py", line 58, in __init__
    raise ValueError('The input parameters {} must be defined.'.format(self._input_parameters - keyset))
ValueError: The input parameters {'TEMPERATURE'} must be defined.
```

I see where the `"Temp"` field is detected (`analysis.py` line 317), but I don't see where value is supposed to be inserted into the `parameters` dict before it's passed in line 393.

[tmp2.txt](https://github.com/sissaschool/sportran/files/10115857/tmp2.txt)

**Comment by bernstei** [comment]
I see that the `"Temp"` column detection is only being done for `lammps` input format. Is there a reason it can't also be done for `table`?

**Comment by bernstei** [comment]
I was able to get it to work (at least that part) by adding `--param-from-input-file-column Temp TEMPERATURE --param-from-input-file-column Volume VOLUME`, but I had expected (based on the `--help` output) that it'd work automatically if the columns had the expected names.
